### ISSUE TITLE
Rewrite parameter generator in Julia

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_datagen_spark#83]
I am currently learning Julia and will use it to take a stab at issue #51, i.e. I'll rewrite the parameter generator (currently implemented in Python 2) in Julia.

I understand that Julia is still a niche language, so users might not be able to trivially install it on their systems. To mitigate this, I'll update the Docker image to support Julia.

The current Docker image is based on Alpine Linux which doesn't have a maintainer for [recent Julia releases](https://pkgs.alpinelinux.org/packages?name=julia&branch=v3.7). Alpine uses `musl libc`, which has only [Tier 3 support in Julia](https://julialang.org/downloads/), which might include test failures (e.g. see [the issue that has only been resolved 11 days ago](https://github.com/JuliaLang/julia/issues/26761)). Therefore I'd just move from `openjdk:8-jdk-alpine` to the Debian-based `openjdk:8-jdk-stretch`. This also has an old Julia version, but it's possible to install with

```console
wget -q https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz
tar xf julia-1.1.1-linux-x86_64.tar.gz
export PATH=$PATH:`pwd`/julia-1.1.1/bin
julia
```

* [x] Update Docker image
* [x] Fix CI to generate the latest set of graphs and parameters (to compare with the ones in stable)
* [x] Migrate BI paramgen script to Julia
  * [x] initial query: Q6
* [ ] Migrate Interactive paramgen script to Julia
* [ ] Integrate parameter generation in the workflow
* [ ] Revisit #51 (Parameter generation is very slow)
* [x] Revisit #59 (PARAM_GENERATION seems deprecated)
* [ ] ~Revisit #69 (BI Q12 substitution parameters have a very high like threshold)~
* [x] Revisit #99 (non-determinism in parameter generator)

The work happens on the [`rework-paramgen`](https://github.com/ldbc/ldbc_snb_datagen/tree/rework-paramgen) branch.

**Comment by szarnyasg** [comment]
Since the generated parameters for BI queries have changed since switching to Hadoop 3.2. and parameter tuning comes at a later stage of benchmark design, we can take a bit more relaxed approach with this task: *Interactive* parameters should be same (or as close as possible) but *BI* parameters are subject to change.

**Comment by szarnyasg** [comment]
Paramgen is going to be reimplemented in SQL.
